Repository 9-1379/T3-R1-BE-Server, pull requests merged in 2024-03, with the labels that each got.

#7 로그인 만들기
  ChangeLog.md
  bhr/.env
  bhr/.gitignore
  bhr/Dockerfile
  bhr/docker-compose.yml
  bhr/pom.xml
  bhr/src/main/java/com/nineties/bhr/annual/domain/Annual.java
  bhr/src/main/java/com/nineties/bhr/annual/domain/AnnualList.java
  bhr/src/main/java/com/nineties/bhr/annual/domain/AnnualPK.java
  bhr/src/main/java/com/nineties/bhr/attendance/domain/Attendance.java
  bhr/src/main/java/com/nineties/bhr/badge/domain/BadgeGrantLog.java
  bhr/src/main/java/com/nineties/bhr/badge/domain/BadgeMaster.java
  bhr/src/main/java/com/nineties/bhr/badge/domain/EmpBadge.java
  bhr/src/main/java/com/nineties/bhr/config/SecurityConfig.java
  bhr/src/main/java/com/nineties/bhr/dept/domain/Dept.java
  bhr/src/main/java/com/nineties/bhr/emp/domain/Code.java
  bhr/src/main/java/com/nineties/bhr/emp/domain/CustomSequenceGenerator.java
  bhr/src/main/java/com/nineties/bhr/emp/domain/Employees.java
  bhr/src/main/java/com/nineties/bhr/emp/domain/Role.java
  bhr/src/main/java/com/nineties/bhr/emp/dto/CustomUserDetails.java
  bhr/src/main/java/com/nineties/bhr/emp/dto/JoinDTO.java
  bhr/src/main/java/com/nineties/bhr/emp/repository/EmployeesRepository.java
  bhr/src/main/java/com/nineties/bhr/emp/service/CustomEmployeeDetailsService.java
  bhr/src/main/java/com/nineties/bhr/emp/service/JoinService.java
  bhr/src/main/java/com/nineties/bhr/jwt/JWTFilter.java
  bhr/src/main/java/com/nineties/bhr/jwt/JWTUtil.java
  bhr/src/main/java/com/nineties/bhr/jwt/LoginFilter.java
  bhr/src/main/java/com/nineties/bhr/login/controller/AdminController.java
  bhr/src/main/java/com/nineties/bhr/login/controller/LoginController.java
  bhr/src/main/java/com/nineties/bhr/login/controller/MainController.java
  bhr/src/main/resources/application.yaml
  bhr/src/main/resources/static/favicon.ico
  bhr/src/main/resources/static/index.html
  bhr/src/main/resources/static/js/app.js
  bhr/src/main/resources/static/js/chunk-vendors.js
  bhr/src/test/java/com/nineties/bhr/emp/repository/EmployeesRepositoryTest.java
Labels: enhancement

#13 로그인 구현
  bhr/src/main/java/com/nineties/bhr/config/SecurityConfig.java
  bhr/src/main/java/com/nineties/bhr/config/WebConfig.java
  bhr/src/main/java/com/nineties/bhr/login/controller/LoginController.java
  bhr/src/main/java/com/nineties/bhr/login/controller/MainController.java
  bhr/src/main/java/com/nineties/bhr/login/dto/RoleInfo.java
Labels: good first issue, merge

#17 신규 직원 생성
  bhr/src/main/java/com/nineties/bhr/config/SecurityConfig.java
  bhr/src/main/java/com/nineties/bhr/dept/repository/DeptRepository.java
  bhr/src/main/java/com/nineties/bhr/emp/domain/Employees.java
  bhr/src/main/java/com/nineties/bhr/emp/repository/EmployeesRepository.java
  bhr/src/main/java/com/nineties/bhr/join/controller/JoinController.java
  bhr/src/main/java/com/nineties/bhr/join/dto/JoinDTO.java
  bhr/src/main/java/com/nineties/bhr/join/dto/JoinPageDTO.java
  bhr/src/main/java/com/nineties/bhr/join/service/JoinService.java
  bhr/src/main/java/com/nineties/bhr/login/controller/LoginController.java
  bhr/src/main/java/com/nineties/bhr/sequence/SequenceTable.java
  bhr/src/main/resources/data.sql
  bhr/src/test/java/com/nineties/bhr/join/service/JoinServiceTest.java
Labels: enhancement, merge

#18 empid, empnum, 부서 목록 신규 직원 생성 창에서 보이도록 수정
  bhr/src/main/java/com/nineties/bhr/dept/dto/DeptNameDTO.java
  bhr/src/main/java/com/nineties/bhr/dept/repository/DeptRepository.java
  bhr/src/main/java/com/nineties/bhr/join/controller/JoinController.java
  bhr/src/main/java/com/nineties/bhr/join/dto/JoinPageDTO.java
  bhr/src/main/java/com/nineties/bhr/join/service/JoinService.java
  bhr/src/main/java/com/nineties/bhr/sequence/domain/SequenceTable.java
  bhr/src/main/java/com/nineties/bhr/sequence/repository/SequenceTableRespository.java
Labels: merge

#19 [Feature]연차 사용 현황 로직
  ChangeLog.md
  bhr/pom.xml
  bhr/src/main/java/com/nineties/bhr/annual/cotroller/AnnualController.java
  bhr/src/main/java/com/nineties/bhr/annual/dto/AnnualListDTO.java
  bhr/src/main/java/com/nineties/bhr/annual/mapper/AnnualMapper.java
  bhr/src/main/java/com/nineties/bhr/annual/repository/AnnualListRepository.java
  bhr/src/main/java/com/nineties/bhr/annual/repository/AnnualRepository.java
  bhr/src/main/java/com/nineties/bhr/annual/service/AnnualListService.java
Labels: good first issue, merge

#20 [Add] 직원 상세정보 로직 추가
  bhr/src/main/java/com/nineties/bhr/config/SecurityConfig.java
  bhr/src/main/java/com/nineties/bhr/emp/controller/EmployeeController.java
  bhr/src/main/java/com/nineties/bhr/emp/dto/EmployeeDTO.java
  bhr/src/main/java/com/nineties/bhr/emp/service/EmployeeService.java
  bhr/src/main/java/com/nineties/bhr/emp/service/EmployeeServiceImpl.java
  bhr/src/main/resources/data.sql
  bhr/src/test/java/com/nineties/emp/controller/EmployeeControllerTest.java
Labels: merge

#21 직원 리스트
  bhr/src/main/java/com/nineties/bhr/config/SecurityConfig.java
  bhr/src/main/java/com/nineties/bhr/emp/controller/HrCardController.java
  bhr/src/main/java/com/nineties/bhr/emp/dto/EmployeeProjection.java
  bhr/src/main/java/com/nineties/bhr/emp/repository/EmployeesRepository.java
  bhr/src/main/java/com/nineties/bhr/emp/service/HrCardService.java
Labels: good first issue, merge
